// src/models/schema/brief.ts
// AI-generated news brief — periodically posted by the beat-patrol agent.
// Each story pitch within the brief can be individually claimed by an author.
import { defineField, defineType } from 'sanity';
import { DocumentTextIcon } from '@sanity/icons';

export default defineType({
  name: 'brief',
  title: 'News Brief',
  type: 'document',
  icon: DocumentTextIcon,
  fields: [
    // ── Brief metadata ──────────────────────────────────────────────────────
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      description: 'e.g. "Morning Brief — April 13, 2026"',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published At',
      type: 'datetime',
      description: 'When this brief was generated by the agent.',
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: 'period',
      title: 'Period',
      type: 'string',
      description: 'Time of day this brief covers.',
      options: {
        list: [
          { title: '🌅 Morning', value: 'morning' },
          { title: '☀️ Afternoon', value: 'afternoon' },
          { title: '🌆 Evening', value: 'evening' },
          { title: '🌙 Night', value: 'night' },
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      type: 'text',
      rows: 3,
      description: 'Brief overview written by the agent — theme, context, or editorial note.',
    }),

    // ── Per-user story passes ───────────────────────────────────────────────
    // Stored at the brief level so individual story status stays globally correct.
    // A pass hides the story from that author's view but leaves it claimable by others.
    defineField({
      name: 'storyPasses',
      title: 'Story Passes',
      type: 'array',
      description: 'Per-author passes on individual pitches.',
      of: [
        {
          type: 'object',
          name: 'storyPass',
          fields: [
            defineField({ name: 'storyKey', title: 'Story Key', type: 'string' }),
            defineField({
              name: 'author',
              title: 'Author',
              type: 'reference',
              to: [{ type: 'author' }],
              weak: true,
            }),
            defineField({ name: 'passedAt', title: 'Passed At', type: 'datetime' }),
          ],
          preview: {
            select: { title: 'storyKey', subtitle: 'author.name' },
          },
        },
      ],
    }),

    // ── Story pitches ───────────────────────────────────────────────────────
    defineField({
      name: 'stories',
      title: 'Story Pitches',
      type: 'array',
      of: [
        {
          type: 'object',
          name: 'storyPitch',
          title: 'Story Pitch',
          fields: [
            defineField({
              name: 'headline',
              title: 'Headline',
              type: 'string',
              description: 'Proposed headline or working title for the story.',
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: 'angle',
              title: 'Angle / Hook',
              type: 'text',
              rows: 3,
              description:
                'The unique angle, under-reported aspect, or editorial hook the agent identified.',
            }),
            defineField({
              name: 'beat',
              title: 'Beat',
              type: 'string',
              description:
                'Coverage area (e.g. Housing, Criminal Justice, Politics, Environment).',
            }),
            defineField({
              name: 'urgency',
              title: 'Urgency',
              type: 'string',
              options: {
                list: [
                  { title: '🚨 Breaking', value: 'breaking' },
                  { title: '🔴 High', value: 'high' },
                  { title: '🟡 Medium', value: 'medium' },
                  { title: '🟢 Low', value: 'low' },
                ],
                layout: 'radio',
              },
              initialValue: 'medium',
            }),
            defineField({
              name: 'sourceSuggestions',
              title: 'Suggested Sources',
              type: 'text',
              rows: 2,
              description: 'Suggested people, agencies, or documents to contact.',
            }),
            defineField({
              name: 'links',
              title: 'Reference Links',
              type: 'array',
              description: 'Source URLs the agent found while patrolling.',
              of: [
                {
                  type: 'object',
                  name: 'referenceLink',
                  fields: [
                    defineField({ name: 'label', title: 'Label', type: 'string' }),
                    defineField({ name: 'url', title: 'URL', type: 'url' }),
                  ],
                  preview: {
                    select: { title: 'label', subtitle: 'url' },
                  },
                },
              ],
            }),

            // ── Claim tracking (written by portal users, not the agent) ──
            defineField({
              name: 'status',
              title: 'Status',
              type: 'string',
              options: {
                list: [
                  { title: 'Unclaimed', value: 'unclaimed' },
                  { title: 'Claimed', value: 'claimed' },
                  { title: 'In Progress', value: 'in_progress' },
                  { title: 'Published', value: 'published' },
                  { title: 'Passed', value: 'passed' },
                ],
              },
              initialValue: 'unclaimed',
            }),
            defineField({
              name: 'claimedBy',
              title: 'Claimed By',
              type: 'reference',
              to: [{ type: 'author' }],
              weak: true,
            }),
            defineField({
              name: 'claimedAt',
              title: 'Claimed At',
              type: 'datetime',
            }),
            defineField({
              name: 'linkedArticle',
              title: 'Linked Article',
              type: 'reference',
              to: [{ type: 'article' }],
              weak: true,
              description: 'Article written from this pitch, once published.',
            }),
          ],
          preview: {
            select: {
              title: 'headline',
              beat: 'beat',
              urgency: 'urgency',
              status: 'status',
            },
            prepare({ title, beat, urgency, status }) {
              const urgencyIcon =
                urgency === 'breaking'
                  ? '🚨'
                  : urgency === 'high'
                    ? '🔴'
                    : urgency === 'medium'
                      ? '🟡'
                      : '🟢';
              return {
                title: title ?? 'Untitled pitch',
                subtitle: `${urgencyIcon} ${beat ?? 'No beat'} — ${status ?? 'unclaimed'}`,
              };
            },
          },
        },
      ],
    }),
  ],

  preview: {
    select: {
      title: 'title',
      period: 'period',
      publishedAt: 'publishedAt',
    },
    prepare({ title, period, publishedAt }) {
      const icons: Record<string, string> = {
        morning: '🌅',
        afternoon: '☀️',
        evening: '🌆',
        night: '🌙',
      };
      const date = publishedAt ? new Date(publishedAt).toLocaleDateString() : '';
      return {
        title: title ?? 'News Brief',
        subtitle: `${icons[period] ?? ''} ${period ?? ''} — ${date}`,
      };
    },
  },

  orderings: [
    {
      title: 'Newest First',
      name: 'newestFirst',
      by: [{ field: 'publishedAt', direction: 'desc' }],
    },
  ],
});
