-- ============================================================
-- UnTelevised Media — digital-books Storage RLS
-- Bucket: digital-books (private)
-- All uploads/deletes: service role only (bypasses RLS)
-- Downloads: via signed URLs generated server-side; no direct
--            anon/user SELECT policy needed.
-- ============================================================

-- Allow service role to manage all objects (service role bypasses RLS by
-- default, but explicit policy keeps intent clear if RLS ever changes).
-- No user-facing policies: downloads are always served as signed URLs
-- generated by the webhook/download API using the service role client.

-- Deny all direct object access from the anon or authenticated roles.
-- (No insert/select/delete policies = deny-all for non-service-role.)

-- Storage policies live in the storage schema:
create policy "digital_books_service_only_insert"
  on storage.objects for insert
  to service_role
  with check (bucket_id = 'digital-books');

create policy "digital_books_service_only_select"
  on storage.objects for select
  to service_role
  using (bucket_id = 'digital-books');

create policy "digital_books_service_only_delete"
  on storage.objects for delete
  to service_role
  using (bucket_id = 'digital-books');
